export const personen = [
	{
		riegeId: 2,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Matthias Hebeisen',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:jugend@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 3,
		riege2Id: 7,
		riege3Id: 4,
		name: 'Sabrina Akeret',
		role: '',
		imageUrl: './images/people/sabrina_akeret_square.jpg',
		mail: 'mailto:jugend@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 4,
		riege2Id: 3,
		riege3Id: 0,
		name: 'Carina Notz',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:jugend@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 0,
		riege2Id: 2,
		riege3Id: 0,
		name: 'Karin Brauchli',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:jugend@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 6,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Martin Bösch',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:info@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Christian Thurnheer',
		role: 'Präsident',
		imageUrl: './images/people/christian2_square.jpg',
		mail: 'mailto:praesi@tvnussbaumen.ch',
		vorstand: true,
		leiter: false,
		riegenleiter: false
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Iren Akeret',
		role: 'Vize-Präsidentin',
		imageUrl: '../images/people/avatar.webp',
		mail: 'mailto:vize@tvnussbaumen.ch',
		vorstand: true,
		leiter: false,
		riegenleiter: false
	},
	{
		riegeId: 1,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Jan Jörg',
		role: 'Oberturner',
		imageUrl: './images/people/jan2_square.jpg',
		mail: 'mailto:oberturnertvnussbaumen.ch',
		vorstand: true,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 5,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Sandro Akeret',
		role: 'Kassier',
		imageUrl: './images/people/sandro_square.jpg',
		mail: 'mailto:kassier@tvnussbaumen.ch',
		vorstand: true,
		leiter: true,
		riegenleiter: true
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Sabrina Sager',
		role: 'Aktuarin',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:sabrina.sager@tvnussbaumen.ch',
		vorstand: true,
		leiter: false,
		riegenleiter: false
	},
	{
		riegeId: 1,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Jasmin Luginbühl',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:info@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: false
	},
	{
		riegeId: 0,
		riege2Id: 5,
		riege3Id: 4,
		name: 'Maurus Vetterli',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:jugend@tvnussbaumen.ch',
		vorstand: false,
		leiter: true,
		riegenleiter: false
	}
];
