export const personen = [
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Matthias Hebeisen',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:christian.thurnheer@bluewin.ch',
		vorstand: false,
		leiter: true
	},
	{
		riegeId: 3,
		riege2Id: 7,
		riege3Id: 0,
		name: 'Sabrina Akeret',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:s.akeret@gmx.ch',
		vorstand: false,
		leiter: true
	},
	{
		riegeId: 4,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Carina Notz',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:iren.akeret.95@hotmail.com',
		vorstand: false,
		leiter: true
	},
	{
		riegeId: 2,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Karin Brauchli',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:iren.akeret.95@hotmail.com',
		vorstand: false,
		leiter: true
	},
	{
		riegeId: 5,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Martin Bösch',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:iren.akeret.95@hotmail.com',
		vorstand: false,
		leiter: true
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Christian Thurnheer',
		role: 'Präsident',
		imageUrl: './images/people/christian2_square.jpg',
		mail: 'mailto:praesident@tvnussbaumen.ch',
		vorstand: true,
		leiter: false
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Iren Akeret',
		role: 'Vize-Präsidentin',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:vize@tvnussbaumen.ch',
		vorstand: true,
		leiter: false
	},
	{
		riegeId: 1,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Jan Jörg',
		role: 'Oberturner',
		imageUrl: './images/people/jan2_square.jpg',
		mail: 'mailto:jan.joerg.jj@gmail.com',
		link: '/erwachsene',
		vorstand: true,
		leiter: true
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Sandro Akeret',
		role: 'Kassier',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:kassier@tvnussbaumen.ch',
		vorstand: true,
		leiter: true
	},
	{
		riegeId: 0,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Sabrina Sager',
		role: 'Aktuarin',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:aktuar@tvnussbaumen.ch',
		vorstand: true,
		leiter: false
	},
	{
		riegeId: 1,
		riege2Id: 0,
		riege3Id: 0,
		name: 'Jasmin Luginbühl',
		role: '',
		imageUrl: './images/people/avatar.webp',
		mail: 'mailto:jasi',
		link: '/jugendriegen',
		vorstand: false,
		leiter: true
	},
];
